### ISSUE TITLE
Ottenere ID Studente

### ISSUE THREAD

**Issue by ghost** [topongo/nuvola#1]
alunni = requests.get('https://nuvola.madisoft.it/api-studente/v1/alunni', headers={"Authorization": f"Bearer {self.token}"}).json()

Questo, è un pezzo preso dal mio script, serve per prendere gli ID di entrambi gli alunni.
for alunno in alunni['valori']:
 print(alunno['id'])

alunno['id'] è l'id studente.

Spero di esserti stato di aiuto

**Comment by topongo** [comment]
Grazie mille del suggerimento, cosa intendi per entrambi gli alunni?
Edit: immaginavo che avrei capito provando, viene ritornati i dati di tutti gli alunni assegnati ad un certo utente (es. se genitore di due alunni si hanno indietro tutti e due) (?)

**Comment by topongo** [comment]
Grazie per aver contribuito al progetto, era da tanto che cercavo quella api call, nel commit 0121b8d357888fccd56785fb23dddc50e958035a ho implementato questa funzionalità.

Thanks for contributing with the project, it has been a long time since I started seeking for that api call, in the 0121b8d357888fccd56785fb23dddc50e958035a commit I implemented these new feature.
